<a href="https://colab.research.google.com/github/magewade/ML_Python_Stepik/blob/main/Copy_of_Copy_of_%D0%9D%D0%BE%D1%83%D1%82%D0%B1%D1%83%D0%BA_%D0%BF%D0%BE_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy (Numeric Python) - библиотека для математических вычислений

Если коротко - это одна из самых базовых библиотек в современном анализе данных на Python, так как с помощью нее можно быстрее и проще обрабатывать данные.

Быстрее за счет того, что основная структура данных - быстрые массивы. Проще -  за счет того, что можно использовать матричные операции, что позволяет избежать циклов, а также многое другое.

Поехали!

### 1. Установка и культура использования

Numpy - это библиотека, а значит пакет, который можно импортировать. Сделать это можно **тремя** способами:

In [1]:
# 1 можно просто импортировать сам пакет и тогда перед каждым вызовом команды необходимо писать название пакета
import numpy

# пример
numpy.array([1,2,3]) 

array([1, 2, 3])

In [2]:
# 2 можно импортировать пакет в текущее окружение и тогда таскать 5 букв n u m p y не нужно!
# но лучше так не делать, потому что библиотека большая и это загрузит память
from numpy import *

# пример
array([1,2,3]) 

array([1, 2, 3])

In [3]:
# 3 но мы рекомендуем использовать следующий способ: импортировать пакет и таскать за собой всего две буквы np
# это повысит читаемость вашего кода - будет ясно, что вы используете встроенную функцию пакета numpy, а не какую-то самописную 
# о поведении которой еще надо догадаться

import numpy as np

# пример
np.array([1,2,3])

array([1, 2, 3])

### 2. Почему Numpy? (подводка к массивам)

В чистом Python нет массивов, но это не мешает программистам внедрять их. Операции со списками в Python долгие и не гибкие для задач анализа данных.

Numpy взялся решить эту проблему. Основная структура данных в numpy - как раз массив (numpy.array - где-то вы эту команду уже видели, не так ли?)

В чем numpy.array красавчик:
* как и вся библиотека numpy он написан на С++, что выделяет операции с ним по скорости
* numpy.array позволяет представлять данные в матричном виде, что позволяет реализовать матричные операции (что быстрее циклов)

Давайте убедимся в этом!

In [4]:
%timeit range(10000)     # обычный range в python
%timeit np.arange(10000) # range из numpy-массива

173 ns ± 36.8 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
7.01 µs ± 2.05 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Ну а теперь идем изучать дальше)

### 3. Начинаем работать с Numpy-массивом! наконец-то)

3.1. Cоздать numpy-массив можно с заранее определенным типом данных

In [5]:
a = np.array([1, 4, 5, 8], dtype=float)
a

array([1., 4., 5., 8.])

In [6]:
a.dtype

dtype('float64')

In [7]:
b = np.array([1, 4, 5, 8], dtype=str)
b

array(['1', '4', '5', '8'], dtype='<U1')

In [8]:
b.dtype # да, вот так странно помечается string

dtype('<U1')

#### Вопрос 1

Узнай, почему string из последнего примера выше помечается как U1. Сначала попробуй догадаться сам, а потом погугли)

#### Задача 1

Вам дан массив, который содержит данные о площади в квадратных футах для домов на определенной улице. 
На этой улице недавно был построен новый дом. 
Измените программу, чтобы она принимала значения для нового дома в качестве входных данных, добавляла его в массив и выводила массив, отсортированный в возрастающем порядке.

In [11]:
data = np.array([1000, 2500, 1400, 1800, 900, 4200, 2200, 1900, 3500])
np.append(data, int(input()))

# put your code here

1200


array([1000, 2500, 1400, 1800,  900, 4200, 2200, 1900, 3500, 1200])

А теперь познакомимся с нашим массивом `а` поближе...

In [12]:
# какой длины ты?

len(a) # внимание, работает только с одномерными этот len

4

In [14]:
# что у тебя на втором месте в массиве?

a[1]

5.0

In [13]:
# че-то не нравится мне этот элемент, давай заменим его!

a[1] = 5
a

array([1., 5., 5., 8.])

In [15]:
# покажи все элементы до 3го (3 - это позиция, отсчет с 0)

a[:2]

array([1., 5.])

In [16]:
# а давай умножим каждый из твоих элементов на число?

a * 2 # пс, то же самое работает с другими арифметическими операциями

array([ 2., 10., 10., 16.])

3.2. Если мы хотим работать с матрицами, то можем создать многомерный массив!

In [17]:
# возьмем новый массив а, чтобы показать другой способ создания массива:
a = np.array(range(10), dtype=float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
# сделаем из него многомерный - 5 строк, 2 столбца
a = a.reshape((5, 2))
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [19]:
# узнаем его размерность
a.shape

(5, 2)

In [20]:
# получим доступ к элементу (теперь мы должны указывать индекс и по строке и по столбцу)

# в левом верхнем углу у нас ....
a[0,0]

0.0

In [21]:
# два или больше массивов можно сконкатенировать при помощи метода concatenate:

a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
# можно указать ось для конкатенации

np.concatenate((a,b), axis=0)

array([1., 2., 3., 4., 5., 6.])

#### Вопрос 2

В аргументах метода reshape можно нередко встретить -1. Что это будет значить?

#### Задача 2

Вам дан массив, который отражает занятость мест в кинотеатре. Место, отмеченное 1, занято, а если место отмечено 0, оно является свободным. 
Однако массив является плоским и одномерным. Преобразуйте его в двумерный массив, который отражает ряды  в зале. 
Каждый ряд в кинотеатре имеет 5 мест, таким образом, всего 30 мест.  
Задайте массиву соответствующую форму и выведите ряд по заданному индексу, который принимается из пользовательского ввода.

In [26]:
data = np.array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0]) 
 
row = int(input())
data.reshape(row, -1)

6


array([[1, 1, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 0, 0],
       [0, 1, 1, 1, 0]])

### 4. Великий Random

В numpy есть встроенный модуль random, позволяющий работать с генерацией случайных чисел. Вот парочка удобных комманд

In [27]:
# создать случайное вещественное число
np.random.randn()

0.6152232790417648

In [28]:
# случайное целое число от 1 до 10
np.random.randint(1,10)

3

In [29]:
# а что если я хочу целых 4 случайных числа?
np.random.randn(4)

array([ 0.55691205,  0.68310108, -0.06188049,  2.31491471])

In [30]:
# ооооо а что если я хочу матрицу из случайных чисел?
np.random.randn(5,3)

array([[ 1.14829142,  1.94871974, -0.2972764 ],
       [-1.21381134, -0.21053883,  0.33169612],
       [ 0.61637385,  0.74986404, -0.83722863],
       [ 1.82327393,  0.78708997, -0.57402777],
       [ 2.21240962,  0.50928967,  1.39690735]])

### Дополнительные материалы



*   Курс по математике в связке с Python, на 2 неделе подробно рассказывается о numpy: 
https://stepik.org/course/3356/promo

*   Курс от МФТИ Python для искуственного интеллекта, в последнем 6 модуле рассказывается про numpy: 
https://stepik.org/course/110361/promo

*  Часовой урок по Numpy на YouTube: 
https://www.youtube.com/watch?v=IWezobwAC-U&ab_channel=%D0%90%D0%B2%D0%B5%D0%9A%D0%BE%D0%B4%D0%B5%D1%80

